---
title: Burger Rush Frontend Structure
---
flowchart TD
    A[Pagina_Web] --> B[template_folder]
    B --> C[templates]
    B --> D[static]
    D --> E[css]
    D --> F[js]
    D --> G[image]
    C --> H[index.html]
    C --> I[cart.html]
    C --> J[menu.html]
    C --> K[signin.html]
    C --> L[signup.html]
    C --> M[point_store.html]
    C --> N[events.html]
    C --> O[blog.html]
    C --> P[contact.html]
    C --> Q[other templates]
    F --> R[main.js]
    F --> S[cart.js]
    F --> T[signup.js]
    F --> U[checkout.js]
    F --> V[cart-effects.js]
    F --> W[auth.js]
    F --> X[other js files]
    E --> Y[style.css]
    E --> Z[other css files]
    G --> AA[images]
