-- MySQL Script generated by MySQL Workbench
-- Sat Mar  8 15:06:38 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Menu_Objetos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Menu_Objetos` (
  `Id_Menu_Objetos` INT NOT NULL,
  `Nombre_Objeto` VARCHAR(45) NOT NULL,
  `Precio` INT NULL,
  `Categoria` VARCHAR(45) NOT NULL,
  `Calorias` INT NULL,
  PRIMARY KEY (`Id_Menu_Objetos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Restaurante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Restaurante` (
  `Id_Restaurante` INT NOT NULL,
  `Restaurante_Address` VARCHAR(45) NULL,
  `Nombre` VARCHAR(45) NULL,
  `Restaurantecol` VARCHAR(45) NULL,
  `Id_Menu_Objetos` INT NOT NULL,
  PRIMARY KEY (`Id_Restaurante`, `Id_Menu_Objetos`),
  INDEX `fk_Restaurante_Menu_Objetos1_idx` (`Id_Menu_Objetos` ASC) VISIBLE,
  CONSTRAINT `fk_Restaurante_Menu_Objetos1`
    FOREIGN KEY (`Id_Menu_Objetos`)
    REFERENCES `mydb`.`Menu_Objetos` (`Id_Menu_Objetos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Metodo_de_Pago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Metodo_de_Pago` (
  `Id_MetodoPago` INT NOT NULL,
  PRIMARY KEY (`Id_MetodoPago`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Address` (
  `Address` VARCHAR(45) NOT NULL,
  `Zip_code` VARCHAR(45) NULL,
  `State` VARCHAR(45) NULL,
  `Country` VARCHAR(45) NULL,
  `City` VARCHAR(45) NULL,
  PRIMARY KEY (`Address`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Transacciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Transacciones` (
  `Id_Transacciones` INT NOT NULL,
  `Puntos_Total` INT NULL,
  `Precio_Total` INT NULL,
  `Objetos` INT NOT NULL,
  `Restaurante` INT NOT NULL,
  `MetodoPago` INT NOT NULL,
  `Address` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Id_Transacciones`, `Objetos`, `Restaurante`, `MetodoPago`, `Address`),
  INDEX `fk_Transacciones_Menu_Objetos1_idx` (`Objetos` ASC) VISIBLE,
  INDEX `fk_Transacciones_Restaurante1_idx` (`Restaurante` ASC) VISIBLE,
  INDEX `fk_Transacciones_Metodo_de_Pago1_idx` (`MetodoPago` ASC) VISIBLE,
  INDEX `fk_Transacciones_Address1_idx` (`Address` ASC) VISIBLE,
  CONSTRAINT `fk_Transacciones_Menu_Objetos1`
    FOREIGN KEY (`Objetos`)
    REFERENCES `mydb`.`Menu_Objetos` (`Id_Menu_Objetos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Transacciones_Restaurante1`
    FOREIGN KEY (`Restaurante`)
    REFERENCES `mydb`.`Restaurante` (`Id_Restaurante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Transacciones_Metodo_de_Pago1`
    FOREIGN KEY (`MetodoPago`)
    REFERENCES `mydb`.`Metodo_de_Pago` (`Id_MetodoPago`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Transacciones_Address1`
    FOREIGN KEY (`Address`)
    REFERENCES `mydb`.`Address` (`Address`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuarios` (
  `Id_Usuario` INT NOT NULL,
  `Nombre_Usuario` VARCHAR(45) NOT NULL,
  `Apellido_Usuario` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Telefono` VARCHAR(45) NULL,
  `Puntos_Acumulados` VARCHAR(45) NULL,
  `Hash_Contrasena_Usuario` VARCHAR(45) NULL,
  `Fecha_Ingresada` VARCHAR(45) NULL,
  `Transacciones` INT NOT NULL,
  `Wallet` INT NOT NULL,
  `Address` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Id_Usuario`, `Transacciones`),
  UNIQUE INDEX `Email_UNIQUE` (`Email` ASC) VISIBLE,
  UNIQUE INDEX `Telefono_UNIQUE` (`Telefono` ASC) VISIBLE,
  UNIQUE INDEX `Hash_Contrasena_Usuario_UNIQUE` (AES_ENCRYPT(`Hash_Contrasena_Usuario`, 'key') ASC) VISIBLE,
  INDEX `fk_Usuarios_Transacciones1_idx` (`Transacciones` ASC) VISIBLE,
  INDEX `fk_Usuarios_Metodo_de_Pago1_idx` (`Wallet` ASC) VISIBLE,
  INDEX `fk_Usuarios_Address1_idx` (`Address` ASC) VISIBLE,
  CONSTRAINT `fk_Usuarios_Transacciones1`
    FOREIGN KEY (`Transacciones`)
    REFERENCES `mydb`.`Transacciones` (`Id_Transacciones`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuarios_Metodo_de_Pago1`
    FOREIGN KEY (`Wallet`)
    REFERENCES `mydb`.`Metodo_de_Pago` (`Id_MetodoPago`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuarios_Address1`
    FOREIGN KEY (`Address`)
    REFERENCES `mydb`.`Address` (`Address`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
